{
  "openapi": "3.0.0",
  "info": {
    "title": "Nutech Test API Docs",
    "description": "Welcome to Nutech Test API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/"
    }
  ],
  "paths": {
    "/api/register": {
      "post": {
        "description": "   Digunakan untuk melakukan registrasi User agar bisa Login kedalam aplikasi.<br>",
        "responses": {
          "200": {
            "description": "Registrasi berhasil silahkan login",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Registrasi berhasil silahkan login",
                  "data": null
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 102,
                  "message": "Parameter email tidak sesuai format",
                  "data": null
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterDTO"
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "post": {
        "description": "   Digunakan untuk melakukan login dan mendapatkan authentication berupa JWT (Json Web Token)<br>",
        "responses": {
          "200": {
            "description": "Login Sukses",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Login Sukses",
                  "data": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 102,
                  "message": "Parameter email tidak sesuai format",
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 103,
                  "message": "Username atau password salah",
                  "data": null
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginDTO"
              }
            }
          }
        }
      }
    },
    "/api/profile": {
      "get": {
        "description": "   Digunakan untuk mendapatkan informasi profile User.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Sukses",
                  "data": {
                    "email": "test@gmail.com",
                    "first_name": "test",
                    "last_name": "test",
                    "profile_image": "https://yoururlapi.com/test.jpeg"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/profile/update": {
      "put": {
        "description": "   Digunakan untuk mengupdate data profile User.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Update Pofile berhasil",
                  "data": {
                    "email": "test@gmail.com",
                    "first_name": "test edited",
                    "last_name": "test edited",
                    "profile_image": "https://yoururlapi.com/test.jpeg"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UserDTO"
              }
            }
          }
        }
      }
    },
    "/api/profile/image": {
      "put": {
        "description": "   Digunakan untuk mengupdate / upload profile image User.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Update Pofile berhasil",
                  "data": {
                    "email": "test@gmail.com",
                    "first_name": "test edited",
                    "last_name": "test edited",
                    "profile_image": "https://yoururlapi.com/test.jpeg"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 102,
                  "message": "Format Image tidak sesuai",
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UserImageDTO"
              }
            }
          }
        }
      }
    },
    "/api/banner": {
      "get": {
        "description": "   Digunakan untuk mendapatkan list banner.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Sukses",
                  "data": [
                    {
                      "service_code": "PGN",
                      "service_name": "PGN Berlangganan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "MUSIK",
                      "service_name": "Musik Berlangganan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "TV",
                      "service_name": "TV Berlangganan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "PAKET_DATA",
                      "service_name": "Paket data",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "VOUCHER_GAME",
                      "service_name": "Voucher Game",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 100000
                    },
                    {
                      "service_code": "VOUCHER_MAKANAN",
                      "service_name": "Voucher Makanan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 100000
                    },
                    {
                      "service_code": "QURBAN",
                      "service_name": "Qurban",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 200000
                    },
                    {
                      "service_code": "ZAKAT",
                      "service_name": "Zakat",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 300000
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/services": {
      "get": {
        "description": "   Digunakan untuk mendapatkan list Service/Layanan PPOB.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Sukses",
                  "data": [
                    {
                      "service_code": "PGN",
                      "service_name": "PGN Berlangganan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "MUSIK",
                      "service_name": "Musik Berlangganan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "TV",
                      "service_name": "TV Berlangganan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "PAKET_DATA",
                      "service_name": "Paket data",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 50000
                    },
                    {
                      "service_code": "VOUCHER_GAME",
                      "service_name": "Voucher Game",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 100000
                    },
                    {
                      "service_code": "VOUCHER_MAKANAN",
                      "service_name": "Voucher Makanan",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 100000
                    },
                    {
                      "service_code": "QURBAN",
                      "service_name": "Qurban",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 200000
                    },
                    {
                      "service_code": "ZAKAT",
                      "service_name": "Zakat",
                      "service_icon": "https://nutech-integrasi.app/dummy.jpg",
                      "service_tariff": 300000
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/balance": {
      "get": {
        "description": "   Digunakan untuk mendapatkan informasi balance / saldo terakhir dari User.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Get Balance Berhasil",
                  "data": {
                    "balance": 1000000
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/topup": {
      "post": {
        "description": "   Digunakan untuk melakukan top up balance / saldo dari User.<br>",
        "responses": {
          "200": {
            "description": "Top Up Balance berhasil",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Top Up Balance berhasil",
                  "data": {
                    "balance": 1900000
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 102,
                  "message": "Paramter amount hanya boleh angka dan tidak boleh lebih kecil dari 0",
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TopUpDTO"
              }
            }
          }
        }
      }
    },
    "/api/payment": {
      "post": {
        "description": "   Digunakan untuk melakukan transaksi dari services / layanan yang tersedia.<br>",
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Transaksi Berhasil",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Transaksi Berhasil",
                  "data": {
                    "invoice_number": "1728750342931",
                    "service_code": "PULSA",
                    "service_name": "Pulsa",
                    "transaction_type": "PAYMENT",
                    "total_amount": 40000,
                    "created_on": "2024-10-12T16:25:42.931Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 102,
                  "message": "Paramter amount hanya boleh angka dan tidak boleh lebih kecil dari 0",
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PaymentDTO"
              }
            }
          }
        }
      }
    },
    "/api/transaction/history": {
      "get": {
        "description": "   Digunakan untuk mendapatkan informasi balance / saldo terakhir dari User.<br>",
        "responses": {
          "200": {
            "description": "Request Successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 0,
                  "message": "Get History Berhasil",
                  "data": {
                    "offset": 0,
                    "limit": 3,
                    "records": [
                      {
                        "invoice_number": "INV17082023-001",
                        "transaction_type": "TOPUP",
                        "description": "Top Up balance",
                        "total_amount": 100000,
                        "created_on": "2023-08-17T10:10:10.000Z"
                      },
                      {
                        "invoice_number": "INV17082023-002",
                        "transaction_type": "PAYMENT",
                        "description": "PLN Pascabayar",
                        "total_amount": 10000,
                        "created_on": "2023-08-17T11:10:10.000Z"
                      },
                      {
                        "invoice_number": "INV17082023-003",
                        "transaction_type": "PAYMENT",
                        "description": "Pulsa Indosat",
                        "total_amount": 40000,
                        "created_on": "2023-08-17T12:10:10.000Z"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "status": 108,
                  "message": "Token tidak tidak valid atau kadaluwarsa",
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "RegisterDTO": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string",
            "minLength": 8
          }
        },
        "required": ["firstname", "lastname", "email", "password"]
      },
      "LoginDTO": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string",
            "minLength": 8
          }
        },
        "required": ["email", "password"]
      },
      "UserDTO": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          }
        },
        "required": ["firstname", "lastname"]
      },
      "UserImageDTO": {
        "type": "object",
        "properties": {
          "image": {
            "type": "file"
          }
        },
        "required": ["image"]
      },
      "TopUpDTO": {
        "type": "object",
        "properties": {
          "top_up_amount": {
            "type": "number",
            "min": 1
          }
        },
        "required": ["top_up_amount"]
      },
      "PaymentDTO": {
        "type": "object",
        "properties": {
          "service_code": {
            "type": "string"
          }
        },
        "required": ["service_code"]
      }
    }
  },
  "server": [
    {
      "url": "http://localhost:3000"
    }
  ]
}
